---
#
#   2017
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: "2.1.1 - Check if telnet server is installed (Scored)"
    shell: rpm -q telnet-server
    register: out211
    ignore_errors: true
    changed_when: false
    failed_when: >
      out211.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.1
      - 2.1.1

  - name: "2.1.2 - Check if telnet client is installed (Scored)"
    shell: rpm -q telnet
    register: out212
    ignore_errors: true
    changed_when: false
    failed_when: >
      out212.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.2
      - 2.1.2

  - name: "2.1.3 - Check if rsh-server is installed (Scored)"
    shell: rpm -q rsh-server
    register: out213
    ignore_errors: true
    changed_when: false
    failed_when: >
      out213.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.3
      - 2.1.3

  - name: "2.1.4 - Check if rsh is installed (Scored)"
    shell: rpm -q rsh
    register: out214
    ignore_errors: true
    changed_when: false
    failed_when: >
      out214.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.4
      - 2.1.4

  - name: "2.1.5 - Check if nis client is installed (Scored)"
    shell: rpm -q ypbind
    register: out215
    ignore_errors: true
    changed_when: false
    failed_when: >
      out215.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.6
      - 2.1.5

  - name: "2.1.6 - Check if nis client is installed (Scored)"
    shell: rpm -q ypserv
    register: out216
    ignore_errors: true
    changed_when: false
    failed_when: >
      out216.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.6
      - 2.1.6
  - name: "2.1.7 - Check if tftp is installed (Scored)"
    shell: rpm -q tftp
    register: out217
    ignore_errors: true
    changed_when: false
    failed_when: >
      out217.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.7
      - 2.1.7

  - name: "2.1.8 - Check if tftp-server is installed (Scored)"
    shell: rpm -q tftp-server
    register: out218
    ignore_errors: true
    changed_when: false
    failed_when: >
      out218.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.8
      - 2.1.8

  - name: "2.1.9 - Check if talk is installed (Scored)"
    shell: rpm -q talk
    register: out219
    ignore_errors: true
    changed_when: false
    failed_when: >
      out219.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.9
      - 2.1.9

  - name: "2.1.10 - Check if talk-server is installed (Scored)"
    shell: rpm -q talk-server
    register: out2110
    ignore_errors: true
    changed_when: false
    failed_when: >
      out2110.rc == 0
    tags:
      - scored
      - section2.1
      - section2.1.10
      - 2.1.10

  - name: "2.1.12 - Disable chargen-dgram (Scored)"
    shell: chkconfig --list chargen-dgram
    register: out2112
    ignore_errors: true
    changed_when: false
    failed_when: >
      out2112.rc == 0 and ':on' in out2112.stdout 
    tags:
      - scored
      - section2.1
      - section2.1.12
      - 2.1.12

  - name: "2.1.13 -  Disable chargen-stream (Scored)"
    shell: chkconfig --list chargen-stream
    register: out2113
    ignore_errors: true
    changed_when: false
    failed_when: >
      out2113.rc == 0 and ':on' in out2113.stdout 
    tags:
      - scored
      - section2.1
      - section2.1.13
      - 2.1.13

  - name: "2.1.14 -  Disable daytime-dgram (Scored)"
    shell: chkconfig --list daytime-dgram
    register: out2114
    ignore_errors: true
    changed_when: false
    failed_when: >
      out2114.rc == 0 and ':on' in out2114.stdout 
    tags:
      - scored
      - section2.1
      - section2.1.14
      - 2.1.14

  - name: "2.1.15 -  Disable daytime-stream (Scored)"
    shell: chkconfig --list daytime-stream
    register: out2115
    ignore_errors: true
    changed_when: false
    failed_when: >
      out2115.rc == 0 and ':on' in out2115.stdout 
    tags:
      - scored
      - section2.1
      - section2.1.15
      - 2.1.15

  - name: "2.1.16 -  Disable echo-dgram (Scored)"
    shell: chkconfig --list echo-dgram
    register: out2116
    ignore_errors: true
    changed_when: false
    failed_when: >
      out2116.rc == 0 and ':on' in out2116.stdout 
    tags:
      - scored
      - section2.1
      - section2.1.16
      - 2.1.16

  - name: "2.1.17 -  Disable echo-stream (Scored)"
    shell: chkconfig --list echo-stream
    register: out2117
    ignore_errors: true
    changed_when: false
    failed_when: >
      out2117.rc == 0 and ':on' in out2117.stdout 
    tags:
      - scored
      - section2.1
      - section2.1.17
      - 2.1.17

  - name: "2.1.17 - Disable tcpmux-server (Scored)"
    shell: chkconfig --list tcpmux-server
    register: out2118
    ignore_errors: true
    changed_when: false
    failed_when: >
      out2118.rc == 0 and ':on' in out2118.stdout 
    tags:
      - scored
      - section2.1
      - section2.1.18
      - 2.1.18
